### ISSUE TITLE
Subtitle extract feature doesn't work for some people

### ISSUE THREAD

**Issue by iPzard** [iPzard/mkvtoolnix-batch-tool#77]
**🦟 Describe the bug**
Some users have reported the extract subtitles feature doesn't work for them, based on the input it appears to be an environmental factor.  Once https://github.com/iPzard/mkvtoolnix-batch-tool/issues/76 is complete, hopefully we can shed more insight on this. 

**Expected behavior**
Subtitles should be extracted when extract feature is used.

**Comment by iPzard** [comment]
https://github.com/iPzard/mkvtoolnix-batch-tool/issues/76 has been wrapped up, waiting for additional user feedback on this.

**Comment by Rayman24365** [comment]
Unfortunately it still fails here. On *any* file, so most likely not specific file related but rather a system thing.
The debug window shows good feedback when removing subs and all works well.
When removing subs I get what seems like a 500 error?

127.0.0.1 - - [27/Feb/2023 10:07:15] "GET /socket.io/?EIO=3&transport=polling&t=OQI82Gk&sid=a76cd2fc32d94a50923a1bed005206ed HTTP/1.1" 200 -
127.0.0.1 - - [27/Feb/2023 10:07:15] "POST /process_batch HTTP/1.1" 500 -
127.0.0.1 - - [27/Feb/2023 10:07:15] "GET /socket.io/?EIO=3&transport=polling&t=OQI84c_&sid=a76cd2fc32d94a50923a1bed005206ed HTTP/1.1" 200 -

**Comment by ElimGarak72** [comment]
It happened the same to me. I used as input a folder with two mkv files inside: one with subtitles in it and one without.

**Comment by iPzard** [comment]
Thanks guys! Can you check which version of the app you're using?

That error should be resolved as of the latest version _(which was released late last night)_, so It seems you both may not be using [v2.5.3](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.5.3) yet.

This error in particular was created by the app calling the `ffprobe` command outside of the `ffmpeg-python` app, which is no longer the case in the latest version. 

In Windows, you can check the version on the add/remove programs screen. You'll want to completely remove the app and install 2.5.3, after that, you shouldn't get this error anymore. 

Check it out and let me know what you guys find out.

**Comment by ElimGarak72** [comment]
Hi and first of all thank you!
I was already using 2.5.3, but I removed it and reinstalled it anyway and I still get the ffprobe error.

All my best,
Fabio

**Comment by iPzard** [comment]
Thanks for confirming! I'll see if I can reproduce on another machine. Is this happening with all files you try?

If you got the release last night.. there's one other thing worth trying, if you get a fresh download of 2.5.3 from the release page, it might help.. I had to update the file about an hour after the original upload because of an issue I found. 

Either way, I'll assume you're on the latest and see what I can find out. Thanks again!

**Comment by Rayman24365** [comment]
I too removed and reinstalled with the file from the release page I just downloaded again.
All files give me this error.

**Comment by iPzard** [comment]
I think I might see what this issue is.. it looks like one of the packages [requires](https://github.com/kkroening/ffmpeg-python#installing-ffmpeg) ffmpeg to be installed and available on the user's system path. This is obviously not something I want the user to need to do, I can just set the program to check and pull the data to the program's %appdata% file, and use it from there if needed.  

One way to check is if you open a Windows terminal _(Windows menu → type cmd → press enter)_, and type ffmpeg and hit enter, what do you see? Does it give you details about ffmpeg and version information, or some sort of error, like `ffmpeg: command not found` or something?

If it's showing an error.. I can make some updates and post an updated installer here for you guys to try before publishing it as a release.

**Comment by ElimGarak72** [comment]
Hi!
I get the error, something like "Program or command not found".

**Comment by iPzard** [comment]
Ok, I think this will do it.. I published it as a pre-release just in case it doesn't. I'll make it an official version once we confirm it works. Give it a shot and let me know how it goes! 

https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.5.4

**Comment by ElimGarak72** [comment]
Hi and thanks again.
Unfortunately, something is still wrong.
Whenever I try to extract a subtitle, I get this error message:
"Error extracting subtitles: [WinError 2]
Can't find the file"

I have tried with two different files in two different folders, both of them having subtitles.

Remove works fine, I did not try Merge.

Thank you!

**Comment by iPzard** [comment]
Thanks for checking! I see the problem, I was able to reproduce on my end.. will try to get a fix up here shortly.

**Comment by ElimGarak72** [comment]
Hi! Are you joking? Thank YOU for all your help and support.
I have quickly checked with one file and it seemed to work.

**Comment by Rayman24365** [comment]
I’m away for a few days but I’ll get to thorough testing when I get back, though it already sounds promising. And indeed, WE should thank YOU for making this amazing tool!
It’s unique in its kind and I’m grateful to ‘get in’ at ground level. It has amazing potential as there’s more it could be doing down the line (i.e. audio as well).
Gratitude 🙏🏻

**Comment by iPzard** [comment]
Sweeet! Glad it's working for both of you, let me know if any other problems come up. Gonna close this ticket.
